### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by tomwhoiscontrary** [tdunning/t-digest#104]
A cursory search didn't find any mention of the thread-safety of a TDigest. I would naively assume that updating a digest is not thread-safe, but reading from one is. However, the comment on TDigest::compress mentions that "This is a destructive operation that is not thread-safe". That sort of implies that other operations, which don't have that note, are thread-safe.

Could you add a sentence to the readme outlining the thread safety situation?

**Comment by tdunning** [comment]
Great idea.

Your basic idea is correct, but even read operations may not see consistent
values unless some care is taken with memory boundaries and caching. Better
to simply assume that t-digest isn't thread safe and put controls outside.

But I will update the readme.
