### ISSUE TITLE
Clearing a TDigest

### ISSUE THREAD

**Issue by tomwhoiscontrary** [tdunning/t-digest#105]
I have a use case where i would like to accumulate statistics on a process, and every now and then, record the current statistics and start collecting fresh ones. The fresh statistics should not include any samples from before the fresh start, to avoid double counting.

Is there any way to reset the counts in a TDigest? If not, would it be plausible to add one?

Is it likely that reusing a TDigest will be significantly cheaper than creating a fresh one? Is it likely that carrying over the centroids (without the counts) will improve accuracy in the long run?

**Comment by tdunning** [comment]
Yeah. Just stash the old digest and create a new one. For the merging
digest, creating a new digest is really cheap. Also, it is really helpful
to start writing to the new digest before you do the writing. You could
overlap writes to the new digest by using ping pong digests but just using
a new one is easier.

Each write takes about 100ns, more or less, depending a bit on your
processor, of course. Allocating a new digest only costs a few array
allocations plus the digest structure itself.  There is no allocation
during normal ops.

Clearing a merging digest would involve resetting a few indexes and
accumulators. This would be cheaper, but not by much.

Other kinds of different are much more complex to clear and it isn't clear
that there is any win.

Overall, I think new allocation is almost always going to be better
balancing complexity against the very small perf win.

**Comment by tomwhoiscontrary** [comment]
Thanks for the info, that makes everything pretty clear.

FWIW, i ended up making a simple generic pool, adding samples to a digest drawn from the pool, and then summing up all the digests in the pool when i need to record the statistics:

```java
// create the pool
private final Pool<TDigest> digestPool = new Pool<>(() -> TDigest.createDigest(100));

// update a digest in the pool
digestPool.accept(d -> d.add(latency));

// destructively drain the pool, and add up the drained digests
TDigest digest = TDigest.createDigest(100);
digestPool.drain().forEach(digest::add);
````

The pool itself is a masterpiece of overengineering, and may or may not actually be correct and/or thread safe:

```java
public class Pool<T> {

    private final Supplier<T> factory;
    private final List<T> elements;

    public Pool(Supplier<T> factory) {
        this.factory = factory;
        elements = new ArrayList<>();
    }

    public void accept(Consumer<T> consumer) {
        T element = acquire();
        try {
            consumer.accept(element);
        } finally {
            release(element);
        }
    }

    private T acquire() {
        synchronized (elements) {
            int size = elements.size();
            if (size > 0) return elements.remove(size - 1);
        }
        return factory.get();
    }

    private void release(T element) {
        synchronized (elements) {
            elements.add(element);
        }
    }

    public List<T> drain() {
        List<T> drained;
        synchronized (elements) {
            drained = new ArrayList<>(elements);
            elements.clear();
        }
        return drained;
    }

}
```

**Comment by tdunning** [comment]
Pools are a fine thing but may be kind of expensive relative to data
insertion. You definitely don't want to hit a synchronized block every time
you insert data. Likewise, you don't want to have a t-digest that moves
from thread to thread.

ThreadLocal would be another option. I don't know if that would actually be
a win.
