### ISSUE TITLE
Performance Improvement Opportunities

### ISSUE THREAD

**Issue by marccelani** [tdunning/t-digest#106]
I've implemented a C++ version of T-Digests and have some suggestions based on my tests.

**Choice of k(q, d)**
I believe that a good function k requires 3 properties:

  - The value of the function k(0, delta) = 0, and k(1, delta) = delta.	
  - The limit of the derivative of the function dk/dq at 0 is inf, and at 1 is inf. This provides bias to improve accuracy at the tails.
  - The derivative function dk/dq is symmetrical around 0.5.

arcsin functions (and their inverses) are expensive. Consider this alternative:

`
k(q, d) = (q >= 0.5) ?  d - d * std::sqrt(0.5 - 0.5 * q) : d * std::sqrt(0.5 * q);
`

**Finding q_limit in Algorithm 1**

In the paper, q_limits are found by adding 1 to the k value of the centroid being inserted into the compressed digest. See line 13 in Algorithm 1. This makes it impossible to cache the limits across merges, and computing them is expensive because it involves computing both k and k_inv.

Consider this alternative approach:

Add in this initialization line at the top of the algorithm
`
k_limit = 1
`
And replace lines 4 and 13 with:
`
q_limit = k_inv(k++, d)
`
In my tests, both of these changes have had marginal impact on accuracy while improving performance significantly.

**Comment by marccelani** [comment]
Combined, only k_inv is used, and my implementation is as follows:
```
double k_to_q(double k, double d) {
  double k_div_d = k / d;
  if (k_div_d >= 0.5) {
    double base = 1 - k_div_d;
    return 1 - 2 * base * base;
  } else {
    return 2 * k_div_d * k_div_d;
  }
}
```

Which is fast enough for d = 100 that caching hasn't even been all that helpful.

**Comment by tdunning** [comment]
Check out the latest code. It avoids the cost of asin in a couple of ways.
It even avoids the cost of the sqrt.

**Comment by marccelani** [comment]
I think it would be great to reflect the changes in the paper :)

**Comment by marccelani** [comment]
I'll update this thread with benchmark results once the code is publicly available on github.

**Comment by marccelani** [comment]
@tdunning : Here are some benchmark results for you: https://github.com/facebook/folly/blob/master/folly/stats/test/TDigestBenchmark.cpp#L141-L151

These benchmarks are run on an Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz

**Comment by tdunning** [comment]
Interesting.

Do you have any idea about the speed of the add method?

Also, what about the effect of compression factor in speed?

**Comment by marccelani** [comment]
We have accuracy measurements in https://github.com/facebook/folly/blob/master/folly/stats/test/TDigestTest.cpp. We measure a bunch of random merges and then take a standard deviation of error, with multimodal logarithmic and normal distributions. Accuracy is very good.

**Comment by marccelani** [comment]
@tdunning : Did you have a chance to review these links, and give thoughts to making these changes to the algo/paper?

Separately, if these benchmarks look good, would you consider pointing to the folly implementation of t-digests?

**Comment by tdunning** [comment]
I did look at some of the links that you provided. But I was pretty sure
that I wasn't able to understand entirely what you were suggesting. For
instance, I wasn't sure what the numbers in the Benchmark results were
actually representing ... how does these numbers relate to the existing
numbers for the system.

I think I understand they are proposing that there be a thread specific
buffer for data that ultimately gets added to a t-digest. Other people have
done something similar bye simply having a thread specific t-Digest. This
is very similar to what you suggest except that individual threads can do
merges independently, and that means that they have to merge to the central
copy much less often. I substantially expect however that I've
misinterpreted some of what you suggested and that's what I'm saying
doesn't entirely make sense.

You also suggest you doing it in place merge during the merging of data and
particularly in the merging of t-tigests. I think that sounds like a great
idea and should help pretty much any implementation. That doesn't sound
like a major change however and what you were suggesting did seem like you
had something bigger in mind.

Regarding a link to Folly I think that's a great idea. Can you say more
about what Folly is and what people should know about it? Also an
indication of how it relates to T digest would be good so that readers
would understand where they're going and why.

**Comment by marccelani** [comment]
> I did look at some of the links that you provided. But I was pretty sure
> that I wasn't able to understand entirely what you were suggesting. For
> instance, I wasn't sure what the numbers in the Benchmark results were
> actually representing ... how does these numbers relate to the existing
> numbers for the system.

Ok I'll try to walk through the numbers.

https://github.com/facebook/folly/blob/master/folly/stats/test/TDigestBenchmark.cpp#L141-L151 is a benchmark of merge, mergeDigests, and estimateQuantile.

merge(100x1) - the time it takes to merge a digest with compression factor 100 with a buffer of size 100.
merge(100x10) - compression factor 100, buffer size 1000.

mergeDigests(100x10) - the time it takes to merge 10 digests with compression factor 100.
mergeDigests(100x60) - the time it takes to merge 60 digests with compression factor 100.

estimateQuantile(100_p50) - the time it takes to estimate p50 on a digest with compression factor 100.
estimateQuantile(100_p99) - the time it takes to estimate p99 on a digest with compression factor 100.

These benchmarks are run on a Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz.

This diff implemented the second recommendation in the original post, and you can see the impact on the benchmarks:
https://github.com/facebook/folly/commit/5ab8094fbc9be0b35a1965cc23f04eb39a97b375#diff-8e165a268a150dbd37e37043b6fecb5e

It basically doubled the performance.

I never committed a diff with arcsin, so I don't have a comparison between the two. But there are some blog posts about how much more expensive sin/atan is compared to sqrt: http://www.latkin.org/blog/2014/11/09/a-simple-benchmark-of-various-math-operations/

> Other people have done something similar bye simply having a thread specific t-Digest. This
> is very similar to what you suggest except that individual threads can do
> merges independently, and that means that they have to merge to the central
> copy much less often.

We actually do both, but with cpu-local data structures instead of thread-local (facebook services tend to have far more threads than cores). https://github.com/facebook/folly/blob/master/folly/stats/detail/DigestBuilder.h#L56-L61

Our default is to have a digest of size 100, with buffer of size 1000. So each cpu will buffer 1000 values, then merge them into a cpu-local digest. Every 1 second, we merge the cpu-local digests and unfilled buffers together into a single digest that is used for estimates.

> Can you say more about what Folly is and what people should know about it? 
Folly is Facebook's open source c++ library. It does all sorts of stuff, not just stats. Folly is designed for high performance use cases in mind. We are beginning to use t-digests for quantile estimation in our c++ services, and our implementation is found in https://github.com/facebook/folly/tree/master/folly/stats (see QuantileEstimator and TDigest). I guess what's interesting about this implementation is that it's built for speed. Everything is designed to minimize contention, cache misses, mallocs, expensive sorts, and expensive floating point operations.

**Comment by marccelani** [comment]
It's also worth noting that the algorithm in the paper does some unnecessary computation. Slightly rewriting the algorithm results in big speedups by avoiding floating point operations:

https://github.com/facebook/folly/commit/7aff14284a66dbec002276b4af5e6f4d5e2b8a3a#diff-8e165a268a150dbd37e37043b6fecb5e

I noticed that the java implementation is already doing many of these optimizations.

**Comment by tdunning** [comment]
OK. I didn't click to the significance of the diffing of the results.  Doh.

Regarding square roots and arcsins and such, the current Java version
doesn't have any. Just a few multiplications and divisions. My guess is
that your code has rounded off a few more edges and is faster, but probably
not by a large amount (I think I remember single add's with roughly 10x
buffer size are around 5ns under not very comparable conditions).

**Comment by tdunning** [comment]
Thanks, btw, for all the context.

I am happy to put in a reference in the README. In fact, if you would like
to send me a pull request, I will just suck it in. That will be faster.

My current work is

a) improving accuracy a fair bit while breaking out and simplifying the
quality testing

b) finishing the paper and bringing it up to the current state

c) splitting small considerations into separate micro-papers


​

**Comment by tdunning** [comment]
Reviving this a bit ...

I have revamped the interpolation codes a fair bit. The result is much improved tail accuracies. It might be worth your while checking it out.

**Comment by tdunning** [comment]
Closing due to idle thread
