### ISSUE TITLE
Please add link to Rust implementation

### ISSUE THREAD

**Issue by JimCooke** [tdunning/t-digest#109]
I have a working Rust implementation you can add to your links.  I will still be adding a few bits to it, but it works.  https://github.com/JimCooke/t-digest

**Comment by tdunning** [comment]
Happy to do so.

If you send a README pull request, it will happen sooner.

Also, what testing do you do for accuracy?

**Comment by JimCooke** [comment]
Thanks, will do.

For the testing, I’m in the process of running through that now and over the next week or so before I release it as a Rust crate.  I am using lists of 1000 numbers, both random and normally distributed in random order, sorted ascending and sorted descending.  I compare the the 05. 1, 5, 10, 25, 50, 75, 90, 95, 99, 99.5 quantiles against correct values that I create using a spreadsheet, and they are checking out well.

With your experience, do you have other suggested strategies or data sets and results that I should use … I guess ones that could cause problems for the algorithm?  I would be keen to test against those.
 I’ll include test sets and results in the GitHub when I do my final commit prior to releasing as a crate.

Regards
Jim Cooke

**Comment by tdunning** [comment]
Check out the tests for the Java version. From memory, these need to
include:

- very large (>100,000) data sets, uniform and very skewed distributions
- very small (<100) data sets
- sorted and reverse sorted (which can affect accuracy and size)
- mixed continuous and discrete distributions
    * important to have one option here that has many, many samples at a
single point and all other points uniform, but to one side of the mass
- discrete distributions

Look at quantiles versus computed values from the original data
Look at number of centroids in the results
Look at error relative to minimum distance to 0 or 1
Verify that all centroids meet the size and delta k criteria
Verify that the sum of centroid weights equals the number of samples seen

Verify all of the accuracies for direct insertion as well as for merging of
multiple digests.

**Comment by tdunning** [comment]
Just a quick note before closing this issue, you should be testing with lots of repeated values as well. A test with 10,000 points with only 5 distinct values for instance. Make sure that the centroid sizes meet the constraint imposed by the scale function.

This is a problem if your sort is unstable because when means are identical and the sort is unstable, heavy centroids can sort too close to the extreme ends of the digest. That can lead to worse accuracy in some nasty cases.
