### ISSUE TITLE
Memory leak in java implementation?

### ISSUE THREAD

**Issue by atronchi** [tdunning/t-digest#111]
First, thanks for making such an excellent toolkit!

There seems to be a possible memory leak or other finite memory related issue in the java implementation. I've found that when ingesting more than about 1M records (e.g. 1M works fine, but not 10M+), the JVM dies with `java.lang.OutOfMemoryError: Java heap space`. 

We've taken care to avoid keeping such large datasets all in memory at once, and other operations (min/max/count/etc) seem to work fine so I'm fairly confident that this is specific to the t-digest implementation and not some other issue with how we're handling data.

Has anyone else run into this or found any sort of work around?

**Comment by tdunning** [comment]
Tell me more.

Which digest are you using?

Have you turned on data recording by accident (most digests will record all
their input if asked, for debugging purposes)?

Can you make a test available to demonstrate the problem?

The production versions of t-digest (AvlTreeDigest and MergingDigest)
should be very well behaved. Memory for AvlTreeDigest should increase with
the log of  your input size, while MergingDigest should be absolutely
static in size with no allocation at all after initialization.

**Comment by atronchi** [comment]
Sorry for the false alarm, but I think the memory errors were unrelated to t-digest. Thanks for making this awesome tool!
