### ISSUE TITLE
  throw new IllegalStateException("Can't happen ... loop fell through");

### ISSUE THREAD

**Issue by smccauliff** [tdunning/t-digest#112]
throw new IllegalStateException("Can't happen ... loop fell through");

This gets thrown when calling MergingDigest.cdf after many tdigests have been merged together.  Any ideas how this would happen?

**Comment by tdunning** [comment]
Wow.

No idea.  That is what I meant with "Can't happen".  Basically what
happened is that the assumption that the loop would always terminate is
clearly wrong.

Can you point to a line number?

**Comment by smccauliff** [comment]
MergingDigest.java:652

I see that mean[n] is NaN and so this check (on line 637) will not pass:
if (mean[it] <= x && mean[it + 1] > x) {

So the loop will exit and the exception will be thrown.

**Comment by tdunning** [comment]
OK.

mean[n] being NaN is also "impossible", so this is useful.

**Comment by tdunning** [comment]
I wonder if this is actually an edge condition due to some accumulated
errors.  Hmmm....

Or the approximate centroid size limit is biting somehow.

**Comment by tdunning** [comment]
This hasn't been reported lately and lots of changes have been made that likely fixed it.

Closing as WONTFIX
