### ISSUE TITLE
dead loop on version 3.1 ? 

### ISSUE THREAD

**Issue by Allchin** [tdunning/t-digest#116]
hi all ,
it seems there is a  proplem in our application with t-digest  3.1 .
some hours after application started ,
cpu of one jvm going to really high (400%)

and analysied with top -H and jstack ,
we found  the most cpu cost stack trace : 
at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:99)
	at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:67)
	at com.tdunning.math.stats.AbstractTDigest.add(AbstractTDigest.java:154)

and 
 there is the code : 
       
            for (int neighbor = start; neighbor != lastNeighbor; neighbor = summary.next(neighbor)) {
                assert minDistance == Math.abs(summary.mean(neighbor) - x);

we use t-digest in a concurrent environment 

is AVLTreeDigest.add(AVLTreeDigest.java:99)  NOT thread safe ?

**Comment by Allchin** [comment]
Now im sure that is not thead safe .closed .

**Comment by tdunning** [comment]
I don't think that any of the implementations of t-digest is thread safe.

Going forward, MergingDigest is the focus of development.
