### ISSUE TITLE
New port to kotlin multiplatform available(+ question about updating samples)

### ISSUE THREAD

**Issue by beyondeye** [tdunning/t-digest#129]
Hi
thanks for your work on the tdigest algorithm and making it available as a high quality Java reference implementation.

I have just completed a port to Kotlin multiplatform of the latest version of the code (see [here](https://github.com/beyondeye/tdigest_kotlin_multiplatform) ) including the original  suit of java unit tests.

I have read the paper and looked into the code of AVLTreeDigest and I have managed to implement the new functionality of **updating** a previously added sample. (see code [here](https://github.com/beyondeye/tdigest_kotlin_multiplatform/blob/66954b371576572409a6aca90fe6afb7a88ab70f/src/commonMain/kotlin/com/tdunning/math/stats/AVLTreeDigest.kt#L168-L252)) 
The code is still experimental, but it is working
My question is: do you think that similar functionality could be added also to MergeDigest?

**Comment by tdunning** [comment]
Are you sure that updating is a good idea?

The problem is that if you pull samples from the wrong places in a distribution, the digest invariant will no longer hold and you lose any accuracy bounds.

**Comment by tdunning** [comment]
Closing this as will-not-fix
