### ISSUE TITLE
LICENSE does not have year and name of copyright owner

### ISSUE THREAD

**Issue by yihua** [tdunning/t-digest#130]
The LICENSE file has the following line which does not look right:
```
Copyright {yyyy} {name of copyright owner}
```
Without the correct information, I cannot add the license to a legal notice.

**Comment by tdunning** [comment]
Thanks. I will fix it.

**Comment by tdunning** [comment]
Actually, on looking at this, I am not sure why you need this. You should reproduce the content of the NOTICE file in your NOTICE file. But the copyright of the code vests in the authors without the need for any notice in the work. The license gives you rights that do not expire and do not depend on the copyright dates.

That said, I would love to help you out.

What is it exactly that you are trying to do? 
What kind of legal notice are you trying to construct?

**Comment by yihua** [comment]
Thanks for the response.  As instructed by our Legal OSS team, I need to manually copy the content of LICENSE as the license attribution of this library to a legal page where licenses of all libraries are shown.  If you could let me know what content I should put in, that'd be great.

**Comment by tdunning** [comment]
Yes. So I would suggest simply copying the content of the Apache license to
your license page. You can find the text in my LICENSE file, or you can
point to the copy on the Apache web site

In your NOTICE file, you should have something like:

We use t-digest which requires the following acknowledgement:
<insert my NOTICE file contents>


You shouldn't need to change anything in the t-digest itself. If it helps
you, I can even move the acknowledgements to a different file which leaves
you with no required change to your NOTICE file.

**Comment by yihua** [comment]
This sounds good to us.  You don't have to change the acknowledgements.  Thanks!

**Comment by tdunning** [comment]
Glad to hear it.

Btw... when you say "our legal OSS team", what company is this?
