### ISSUE TITLE
min/max

### ISSUE THREAD

**Issue by velvia** [tdunning/t-digest#132]
Sorry this may be a dumb question, but how does one find the min and max values tracked by the T-Digest?  Is it simply the first and last centroids?   Some comments in other issues and in docs seem to refer to interpolating to a min and max, so it must be tracked somewhere, but there is no min/max method (at least in the Java implementation)

**Comment by tdunning** [comment]
The min and max values are always tracked implicitly by t-digests if you
use a scaling function other than K_0 (default is K_2, used to be K_1). The
current version of the AVLTreeDigest and the MergingDigest actually retain
these values exactly as well. I believe that these values survive
serialization as well.

To get the best estimate of the min use digest.quantile(0), for max use
digest.quantile(1). It would be reasonable to set up min() and max()
methods as aliases for these calls in the AbstractTDigest class. Doing so
would make a very reasonable pull request if you are so inclined.

There has also been some discussion of adding more information to each
centroid, possible min and max, possibly some moment information. Having
this information might make better interpolation possible, for instance.
There has been no progress on that yet.



It has been a point of some interest to explicitly track min and max

**Comment by tdunning** [comment]
The latest (unreleased) code keep the min and max as singleton centroids.

That means that quantile(0) and quantile(1) will return exact results.
