### ISSUE TITLE
Its not an issue. Its query

### ISSUE THREAD

**Issue by ashokblend** [tdunning/t-digest#140]
We have around 300 user and we have to compute percentile of traffic usage of each user using spark streaming(getting from kafka).

Is there any example which shows how to do it using TDigest

**Comment by tdunning** [comment]
I don't have an example in spark.

I could help you create one if you would like to work together on this.

**Comment by tdunning** [comment]
Do you have an answer to my question about working together?

If not, I will close this issue in a few days.

**Comment by ashokblend** [comment]
Hi, We chose other options. I will close this issue.

**Comment by tdunning** [comment]
Ashok,

Can you say what you chose?
