### ISSUE TITLE
Why only support JDK8?

### ISSUE THREAD

**Issue by jingjiajie** [tdunning/t-digest#146]
I'm using jdk6, and as I add the maven dependency of t-digest library, it throws exception of not supporting jdk version less than jdk8. However, when I copy all the source code into my project and run the code, it seems working well with jdk6. So, is there any reason for why only supporting jdk8? Can I use it under jdk6?

**Comment by tdunning** [comment]
Actually, I think that the guarantee is that it will work with JDK7.

I can't think of anything off-hand that would break on JDK6, but I haven't used that forever. If the unit tests pass, it should be fine.

But why in the world are you using a version that was end-of-life in 20013? Even JDK7 was EOL five years ago!
