### ISSUE TITLE
Why keeps the centroids with same mean after compressed?

### ISSUE THREAD

**Issue by xiezhenye** [tdunning/t-digest#149]
```java
        TDigest tDigest = new MergingDigest(10L);
        for (int i = 0; i < 50; i++) {
            tDigest.add(1, 1);
        }
        System.out.println(tDigest.centroids().size());
        tDigest.centroids().forEach(c -> {
            System.out.printf("%f %d\n", c.mean(), c.count());
        });
```

will prints

```
14
1.000000 1
1.000000 1
1.000000 2
1.000000 3
1.000000 5
1.000000 6
1.000000 7
1.000000 7
1.000000 6
1.000000 5
1.000000 3
1.000000 2
1.000000 1
1.000000 1
```

Why centroids with same mean are not compacted into one centroid? What's the reason to keep these centroid?

**Comment by tdunning** [comment]
That's a great question.

The reason for doing this is to preserve the invariant on cluster size. If a sample is added afterwards and happens to land right next to this collection of centroids, one of them can be peeled off to include this new point (and get a new mean).

Of course, this effect could also be handled by allowing centroids that were formed from just a single value to be split as later, but there currently isn't any mechanism to remember which centroids had a single value and which had different values. Unless we remember that, we can't know if we can split and remembering that requires an extra flag per centroid and extra logic to check and update that flag.

On the other hand, the code as it is works well in this case and others. Moreover, the cost in time is zero and the space required always conforms with the guarantees of the t-digest and thus could be considered nil. If other data points are added, these single value centroids will be merged or be shaved off into adjacent clusters to preserve the invariant.

Does that make sense?

**Comment by tdunning** [comment]
Closing due to lack of response.
