### ISSUE TITLE
K3 function is wrong

### ISSUE THREAD

**Issue by cyb70289** [tdunning/t-digest#151]
https://github.com/tdunning/t-digest/blob/master/core/src/main/java/com/tdunning/math/stats/ScaleFunction.java#L276

Should replace division with multiplication.

wrong: `return Math.log(2 * q) / normalizer;`
correct: `return Math.log(2 * q) * normalizer;`

**Comment by tdunning** [comment]
Is you comment based on analogy with other implementations?  Or did you do a deeper analysis to verify that this is wrong and the others right?

**Comment by cyb70289** [comment]
I implemented a c++ version of t-digest, when evaluating different k functions, I met with big errors from k3 function. I checked your tdigest paper and found this error, replacing division with multitplication fixes the issue.

**Comment by tdunning** [comment]
Thanks for the response.

As the person making the original error, I wanted some confirmation.

Do you want me to link to your implementation?

**Comment by tdunning** [comment]
I just pushed some tests that expose this directly together with your fix. Thanks for the help!!

(I still would love to link to your implementation)

**Comment by cyb70289** [comment]
Thanks @tdunning, I will upload my implementation to [apache arrow](https://github.com/apache/arrow) project. Will give the link when it's ready.

**Comment by tdunning** [comment]
Thanks.

**Comment by tdunning** [comment]
Btw... I just realized that your fix solves a long-standing issue with K_3 that I had not previously understood.

Thanks again.

**Comment by cyb70289** [comment]
@tdunning , my t-digest c++ implementation is merged in apache arrow project. It will be great if you can link it. Thanks.
header: https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/tdigest.h
source: https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/tdigest.cc
unit test: https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/tdigest_test.cc
benchmark: https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/tdigest_benchmark.cc

**Comment by tdunning** [comment]
Happy to link (probably to the .h file and to the project at large)

Is this usable as part of Arrow? And docs on that that I could point to?

**Comment by cyb70289** [comment]
I will use this tdigest lib in followup patches to implement approximate quantile `compute kernel` and `flightrpc` latency estimation.
`compute kernel` and `flightrpc` are all apache arrow components, located in same repo.

**Comment by tdunning** [comment]
OK. No doc link necessary then.
