### ISSUE TITLE
The quality project in the main branch can not be compiled with org.apache.datasketches:1.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by lihanhui** [tdunning/t-digest#164]
No jar 1.4.0-SNAPSHOT found! It should be replaced with  2.0.0
        <dependency>
             <groupId>org.apache.datasketches</groupId>
             <artifactId>datasketches-java</artifactId>
-            <version>1.4.0-SNAPSHOT</version>
+            <version>2.0.0</version>
             <scope>test</scope>
         </dependency>

**Comment by tdunning** [comment]
Yes. You are correct.

I did that last night.

**Comment by tdunning** [comment]
Fixed now.

Thanks for having eagle eyes!
