### ISSUE TITLE
Release 3.3 is broken on maven central

### ISSUE THREAD

**Issue by slandelle** [tdunning/t-digest#172]
t-digest is supposed to have a parent pom.
From https://repo1.maven.org/maven2/com/tdunning/t-digest/3.3/t-digest-3.3.pom:

```xml
<parent>
  <groupId>com.tdunning</groupId>
  <artifactId>t-digest-parent</artifactId>
  <version>3.3</version>
  <relativePath>../parent/pom.xml</relativePath>
</parent>
```

But `t-digest-parent` hasn't been released on maven central.

see https://repo1.maven.org/maven2/com/tdunning/

**Comment by tdunning** [comment]
Thanks for this report.

Do you have a suggestion? I can break the poms apart and re-release, but
might also be able to just release the parent pom. I am unfamiliar with the
process for the second option.

**Comment by slandelle** [comment]
This release can easily be fixed, only the parent pom has to be deployed.
How have you deployed in the first place so that you ended up only deploying the core module?

It should be possible to only deploy the missing file, but I first would like to know more about your current release process.

Personally, I'm not fond of this pom hierarchy where the grand-father is a subdirectory of the root module.

**Comment by tdunning** [comment]
Can you contact me directly on gmail.com as ted.dunning or via DM on twitter? I would love some direct feedback here.

**Comment by slandelle** [comment]
Just shot you an email :)

**Comment by tdunning** [comment]
This seems fixed.
