### ISSUE TITLE
Will merging multiple t-digest preserve the exact value of min/max?

### ISSUE THREAD

**Issue by mqliang** [tdunning/t-digest#190]
Sorry this may be a dumb question

https://github.com/tdunning/t-digest/issues/132 says that the code keep the min and max as singleton centroids, so `getMin()` and `getMax()` will return the exact value.

My question is if I merge multiple t-digests, will it preserve the exact min/max value across multiple t-digest being merged?

**Comment by tdunning** [comment]
Yes. All constraints are preserved when merging valid digests.

That includes that the extreme centroids have weight = 1 which means that
their value is the exact max or min.

**Comment by tdunning** [comment]
And no, it isn't a dumb question. Questions about invariants are never dumb!

**Comment by mqliang** [comment]
Thanks for answering the question!
