### ISSUE TITLE
Merge implementation of MergingDigest

### ISSUE THREAD

**Issue by rnataf** [tdunning/t-digest#200]
Hi, I have a question about the implementation of the merge function of MergingDigest: `private void merge(double[] incomingMean, double[] incomingWeight, int incomingCount, List<List<Double>> incomingData, int[] incomingOrder, double unmergedWeight, boolean runBackwards, double compression)`.  In the loop `for (int i = 1; i < incomingCount; i++) `, what prevents the variable `lastUsedCell` not to increase too much, leading to an illegal access to the array `weight[lastUsedCell]` ? 

I'm asking because I did a small modification to the code (multiplying weights by a constant before continuing adding data, to the object) and it caused `lastUsedCell` to have a bigger value than weight.length.

**Comment by tdunning** [comment]
Normally what prevents this is the scale invariant.

Each of the current scale functions K0 through K3 has an associated proof
that simple merging then centroids of two digests that have the invariant
will result in a digest that satisfies the invariant. Further, there is a
proof that fully merging any digest that meets the invariant will have a
well bounded size.

If you multiply the weights, then you very likely wind up with a digest
that doesn't meet the invariant and that means that all bets are off.

**Comment by rnataf** [comment]
Okay, thank you for your answer.
