### ISSUE TITLE
Question on quantile calculation logic

### ISSUE THREAD

**Issue by kristiantokarim** [tdunning/t-digest#201]
Hello Ted, I'm currently learning more about the t-digest and reading your great paper about it + going through the implementation.

I understand the code in general, except on this part.
https://github.com/tdunning/t-digest/blob/main/core/src/main/java/com/tdunning/math/stats/MergingDigest.java#L778-L782

Based on my understanding, it is to handle case where the requested quantile fall near the end of the last cluster, and we can just apply linear interpolation to get the approximation. However there are few things that does not make sense to me:
1. `z1 = index - totalWeight - weight[n - 1] / 2.0;` -  index value is between [0 to totalWeight](https://github.com/tdunning/t-digest/blob/main/core/src/main/java/com/tdunning/math/stats/MergingDigest.java#L716), so subtracting index with totalWeight then weight[n - 1] / 2.0 will make  z1 < 0. I guess maybe you forgot to add bracket around `totalWeight - weight[n - 1] / 2.0` ? If yes, then it makes sense because `totalWeight - weight[n - 1] / 2.0` is supposed to be location of the last cluster centroid and we can use it for interpolation.
2. `weightedAverage(mean[n - 1], z1, max, z2);` - I tried to manually work out the interpolation function and it should be `weightedAverage(mean[n - 1], z2, max, z1)`. Not sure if I missed anything. Here's my manual work write out:
```
(y - y1) (x2 - x1) = (x - x1) (y2 - y1)
y is the quantile that we want to find out
substitute y1 with mean[n-1]
substitute y2 with max because we want to interpolate out to max
substitute x1 with index of last cluster mid point which is totalWeight - weight[n - 1] / 2.0
substitute x2 with index of max which is totalWeight
substitute x with index of the quantile which is index
And we already know that:
    z1 = index - (totalWeight - weight[n - 1] / 2.0) 
    z2 = weight[n-1]/2 - z1
    z1 + z2  =  weight[n-1]/2
so y = ((x - x1) (y2 - y1) / (x2 - x1)) + y1
   y = ((x - x1) (y2 - y1) + y1 (x2 - x1))/ (x2 - x1)
          x - x1 is (index - (totalWeight - weight[n - 1] / 2.0)) which is z1
          y2 - y1 is (max - mean[n-1])
          x2 - x1 is (totalWeight - (totalWeight - weight[n - 1] / 2.0)) which can be simplify to weight[n - 1] / 2.0 i.e. z1 + z2
   y = ((z1 * ( max - mean[n-1])) + (mean[n-1] *(z1 + z2))) / (z1 + z2)
   y = (z1 * max - z1 * mean[n-1] + z1 * mean[n-1] + z2 * mean[n-1]) / (z1 + z2)
   y =  (z1 * max + z2 * mean[n-1]) / (z1 + z2)
which is weightedAverage(mean[n - 1], z2, max, z1)
```

Would appreciate if you could help me understand this. Let me know if there is anything unclear. Thank you 🙇

**Comment by tdunning** [comment]
I have been thinking about your comments.

My guess is that what you say is correct, but moot.

The reason I say this is that the current algorithms all enforce the
property that the minimum and maximum samples form singleton centroids.
Frankly, this makes the retention of the min and max values redundant, but
it also means that special handling that pretends that the min and max are
separate samples is also incorrect.

The new Julia port of the algorithm uses this to substantially simplify the
interpolation logic. See, for instance, how the max value is retrieved from
the last centroid
<https://github.com/tdunning/TDigest/blob/d3e0883655cdb26efe9c32feda01b918a9978e15/src/TDigest.jl#L350>
and see how the special purpose code for computing cdf at the min value
<https://github.com/tdunning/TDigest/blob/d3e0883655cdb26efe9c32feda01b918a9978e15/src/TDigest.jl#L454-L468>
is
simplified.

I really should go back through the Java code to perform similar
simplifications. Time is difficult to come by, however.

**Comment by kristiantokarim** [comment]
Sorry for just getting back, thank you for the explanation. Understood and will check the julia port of the implementation. Thanks and feel free to close the issue ! 🙇
