### ISSUE TITLE
Test method testScaling() always adds values in ascending order

### ISSUE THREAD

**Issue by oertl** [tdunning/t-digest#29]
The unit test method testScaling() defined in ArrayDigestTest, TreeDigestTest, and AVLTreeDigestTest generates a list of random numbers, sorts them, and always adds them in ascending order to the TDigest data structures. I am not sure if this is on purpose, since adding values in ascending order is a pathologic case.

**Comment by tdunning** [comment]
I am marking this as WONTFIX since I am going to redo the scaling framework as part of this latest release.
