### ISSUE TITLE
Make TDigest serializable

### ISSUE THREAD

**Issue by gregakespret** [tdunning/t-digest#47]
I was wondering why TDigest is not Serializable. I found myself writing some boilerplate code to serialize/deserialize it between tasks when using it in Spark and it would be cool if it was serializable by default. This is what I have to do now:

```scala
def serialize(tdigest: TDigest) = {
  val arr = new Array[Byte](tdigest.byteSize)
  tdigest.asBytes(ByteBuffer.wrap(arr))
  arr
}

def deserialize(arr: Array[Byte]) = {
  AVLTreeDigest.fromBytes(ByteBuffer.wrap(arr))
}
```

Do you have any thoughts on that? I could submit a PR for this if you think it'd be useful.

**Comment by tdunning** [comment]
Hmm...

I really dislike what Serializable does to code.  It is definitely
important to have a way to save data, but it tends to make things really
brittle.

How bad is this for you?

**Comment by gregakespret** [comment]
It's not that bad, I have a working solution and can continue to use it (code above).
