### ISSUE TITLE
MergingDigest.centroids is wrong on an empty digest

### ISSUE THREAD

**Issue by jpountz** [tdunning/t-digest#49]
When calling `centroids` on an empty MergingDigest, a list containing a single element with NaN as a centroid is returned instead of an empty list:

```java
MergingDigest d = new MergingDigest(100);
System.out.println(d.centroids()); // [Centroid{centroid=NaN, count=0}]
```

**Comment by tdunning** [comment]
Oops.  Thanks.

MergingDigest isn't don't yet so I don't want to spin up a new release for this, but it clearly needs fixing.

**Comment by jpountz** [comment]
No worries I'm just plyaing for now. For the record, it's easy to work around by extending MergingDigest.centroids and returning an empty list when size() returns 0.

By the way some initial testing seems to suggest MergingDigest is slower than AVLTreeDigest (at least on a uniform distribution) while I was expecting this impl to be faster?

**Comment by tdunning** [comment]
I haven't touched speed questions yet.  There are knobs to turn still.  I would think it could be faster, but hard to say.  The serious goal is to provide a basis for translation to C.  That means we can't have any dynamic allocation that assumes GC.
