### ISSUE TITLE
jdk8 doclint incompatibility

### ISSUE THREAD

**Issue by judovana** [tdunning/t-digest#58]
Hi!

Library do not compile with jdk8. Main Issue is javadoc error, "self-closing elements not allowed" and "mallformed html"
  -  https://kojipkgs.fedoraproject.org//work/tasks/8668/10158668/build.log
Simple auto-patching of first one can be done:
$ grep -ir -e "<p/>"
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java:     * <p/>
src/main/java/com/tdunning/math/stats/TDigest.java:     * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/TreeDigest.java: * <p/>
src/main/java/com/tdunning/math/stats/ArrayDigest.java: * <p/>
$ sed "s;<p/>;<br>;g"  -i src/main/java/com/tdunning/math/stats/TDigest.java
$ sed "s;<p/>;<br>;g"  -i src/main/java/com/tdunning/math/stats/TreeDigest.java
$ sed "s;<p/>;<br>;g"  -i src/main/java/com/tdunning/math/stats/ArrayDigest.java
$ grep -ir -e "<p/>"

Whether to repalce by <p></p> or <br> or just nothing is up to you.
I went with <br> jsut because it  seemed to be most close to original idea.

Except the self closing element, there is huge nuyber of < and > chas i javadoc whcih have to berepalced by &lt;&gt; . I did this manually.

It resulted to:
http://pkgs.fedoraproject.org/cgit/t-digest.git/tree/jdk8-javadoc.patch?id=7c47e6cf5f8e8b7fd78bda838a78cbadd2da38a1

If you wont me to do an pull request with this patch, or with different replacement, I will be happy to proceed. 

In all cases, it would be nice to have t-digest buildbale by jdk8 (as I have now - http://koji.fedoraproject.org/koji/taskinfo?taskID=10338753)

**Comment by tdunning** [comment]
THanks.

I will get this fixed.

**Comment by tdunning** [comment]
This works for me now.
