### ISSUE TITLE
Which TDigest do you recommend?

### ISSUE THREAD

**Issue by adaviding** [tdunning/t-digest#63]
It looks like you have 4 kinds of TDigest in this codebase.

- AVLTreeDigest
- ArrayDigest
- MergingDigest
- TreeDigest

I cannot tell which implementation is the most highly recommended.  Do you have a suggestion?

I am building a MapReduce job using Apache Spark.

**Comment by adaviding** [comment]
Nevermind.

I just saw the comments to the method `TDigest.createDigest`.  In these comments, you have identified the `AVLTreeDigest`.

**Comment by tdunning** [comment]
Actually, you should call createDigest to create a digest.  That will give you an instance of the current best kind of t-digest.
