### ISSUE TITLE
Release of version 3.2

### ISSUE THREAD

**Issue by poojke** [tdunning/t-digest#67]
Hi,

First up, thanks for releasing the code!

If possible, could you provide an ETA for the release of version 3.2? The recent Serialisation changes (#56) together with the pending PR #66 would allow us to use your library as is.

Thanks

**Comment by tdunning** [comment]
I can't say a date but I am stealing time here and there to make progress.  I would like to introduce the new array form, but may delay that to 3.3 to avoid being too slow. The serialization changes are a big improvement to usability and need to go in.

**Comment by instanceofme** [comment]
Same here, we could use the `Serializable` :)

**Comment by tibidoh** [comment]
H! A kind reminder about releasing the serialization updates.
Meanwhile, would it be possible to have at least a snapshot released with those changes?

**Comment by tdunning** [comment]
Yes.  Thanks for the kind reminder.

A release is absolutely doable.

**Comment by chonton-elementum** [comment]
Anyone ETA?  Do you need help?

**Comment by tdunning** [comment]
That would be grand.

There are just a few main issues before us. Not all are strictly necessary:

1) the tests have grown like topsy over time and it isn't clear that all of
them make sense anymore. That may be why some are failing. Or it could be
good tests finding bad implementation. Either way, this needs to be
resolved before a next release.

2) the accuracy runs need to be repeated with the two main remaining
implementations (AVLTree and MergingDigest).  This information needs to be
summarized in a boring way. And the t-digest-benchmarks need to be updated
and run for the two algorithms in a consistent way.

3) the paper needs updates from (2) and a bit more clarity in the
relationship of the two implementations.

4) the API needs to be cleaned a bit. Old implementations should be pruned
and the default should be addressed. The new merge function from
MergingDigest needs to be promoted to the top-level.

5) The question of serialization should be put to bed and all (two) current
implementations need to be verified to serialize and deserialize correctly.
I would like it if the two implementations could inter-operate as well so
that a MergingDigest could be deserialized from an AVLTree digest. There
should be a default TDigest deserialization as well.

I think that (3) is squishy and not blocking.  Even (4) might be
non-blocking. Items (1) and (5) are definitely blocking and I lean toward
blocking on (2).

Your thoughts?

**Comment by tdunning** [comment]
A release is (really!) coming soon.

Serialization really works now. And there is a roadmap for improvement beyond what we have now.

The API has been cleaned up, the paper is half fixed (I will defer that in favor of getting the release out) and the tests are all clean again.

**Comment by iemejia** [comment]
Big +1 for the new release. Are the blockers still active, anyway we can help getting this out?

**Comment by tdunning** [comment]
Ismaël,

There is one serious potential blocker that I may just take as a known
defect.

See https://github.com/tdunning/t-digest/issues/89

**Comment by tdunning** [comment]
We also have some pending work on serialization. I may accept that as not
done as well and push it to a dot release.

**Comment by iemejia** [comment]
Just wanted to thank you for the release and for this lib in general @tdunning . For info the library is no integrated as an extension in Apache Beam too :)
https://github.com/apache/beam/pull/4611
