### ISSUE TITLE
underlying distribution : powerlaw

### ISSUE THREAD

**Issue by amurthy-perf** [tdunning/t-digest#74]
Could you please explain what is expected if the underlying distribution is a powerlaw (pareto specifically). The deviation of computed 50-pct from real 50-pct ranges from 0.01% to 15%. Furthermore, it deviates based on shuffle.

My data set has 600K data points. Do we have any specific scaling guide to replace `4*q*(1-q)` for powerlaw types.

**Comment by tdunning** [comment]
No special handling will be necessary at all.

T-digest handles distributions that are 10^30 times more skewed than what
you describe without any special handling.
