### ISSUE TITLE
Add serializability

### ISSUE THREAD

**Issue by hackbert** [tdunning/t-digest#76]
We use a patched version of t-digest because we have to send AVLTreeDigest over the wire (because we are using spark) and therefore the class has to be serializable. Would you be open to merge this as a pull request? If so we would provide one.

Btw. thx for this awesome library - saves us a ton of time computing percentiles!

**Comment by tdunning** [comment]
I would be very interested in pull requests.

**Comment by tibidoh** [comment]
Since f4ed7af  TDigest is already implements Serializable, which should be enough for Spark.
I guess the only piece which is missing is to release the code (#67)

**Comment by hackbert** [comment]
You are totally right.

**Comment by tdunning** [comment]
Agree.

I have been working on the branches faster-merge and new-article to get to
where a release will work.

The upshot will be much faster implementation and better accuracy. Also, a
different technology histogram as well.  And serializability.
