### ISSUE TITLE
AVLTreeDigest with a lot of datas : integer overflow

### ISSUE THREAD

**Issue by Nikko78** [tdunning/t-digest#81]
For a spacial project, we use TDigest to make statistics on 5 billion stars. Thanks for your works, it's very useful !

With integer fields, AVLTreeDigest give false results while TreeDigest give good results.

The problem become from "int[] aggregatedCounts", in AVLGroupTree, sometimes sum overflow integer capacity and the result become negative.

I change "int" to "long" and after AVLTreeDigest gave good results (the same result as TreeDigest).

[AVLGroupTree_patch.txt](https://github.com/tdunning/t-digest/files/913642/AVLGroupTree_patch.txt)

**Comment by tdunning** [comment]
Nikko,

Thanks for the feedback.  I think that this has been fixed in the latest
version. Need to get that released.

Also, there is a new algorithm, MergingDigest that should give you a big
speedup. That may not be interesting given that you have done your work
already, but keep it in mind if you need it later.

Do you have a reference for your work yet? I would love to include it as an
example.

**Comment by Nikko78** [comment]
Thanks for your suggestion for MergingDigest, we have a lot of stats to do in the future with new data which will be sent by the satellite.
I'm working on GAIA : http://sci.esa.int/gaia/ in Paris Observatory (http://www.obspm.fr) on CU9 on WP940 (data validation) (http://gaia.ub.edu/?page_id=4320)
Nicolas

**Comment by tdunning** [comment]
I just checked and the MergingDigest accumulates the weights in double. AVLTreeDigest uses int. This means that MergingDigest will work for your case with many counts. I will document the limitation for AVLTreeDigest, but I don't expect that I will change it in the near future.

Thanks for the references!

**Comment by tdunning** [comment]
Also, check out the MegaMergeTest for an example of merging lots of digests at once. This is what you need for parallelism.

Let me know if you publish any papers that describe your use of t-digest so I can make sure to reference them!
