### ISSUE TITLE
TDigest class does not implement Serializable interface in last release.

### ISSUE THREAD

**Issue by Money-Honey** [tdunning/t-digest#82]
Very good library, i have tested it, thanks a lot, however this library can't be used with Spark without implementing TDigest class Serializable interface.

My question is when will be new release with new features, in particular just adding Serializable support? 
Thanks in advance.

**Comment by Money-Honey** [comment]
Not relevant more. 

digest.asBytes + TDigest.fromBytes
+
Effective Java, Chapter 11 way of using custom serialization 
+
AccumulatorV2

work fine. Thanks a lot for library!

**Comment by tdunning** [comment]
New release is coming (slowly) and it will have Serializable.

**Comment by Money-Honey** [comment]
Thanks for answering. It's good news!
