### ISSUE TITLE
Merging of T-Digests produce slightly different results depending upon the order of merge.

### ISSUE THREAD

**Issue by schatterjee10** [tdunning/t-digest#94]
Hi Ted,

   I have been running some tests with your T-Digest Java code to understand the algorithm. I am using MergingDigest implementation. The dataset has about 60k samples. I wanted to slice the samples into three different sets (e.g. set1 = 1-15000, set2 = 15001-45000, set3=45001-60000). I wanted to create partial digests from each of these sets and then merge them into a final set. In two different runs, I have changed the order in which partial digests were added to make final digests. 

  I found that the final median was slightly different in two different passes(i.e. the final median is sensitive to the order in which partial digests were merged). However, the sensitivity also depends on compression factor. If I increase that parameter, eventually the dependency on merge order disappears. Note that this dependency also has connection with input sample distribution. I was able to see this with one sample dataset and not with some other samples. Is this expected from MergingDigest algorithm? 

Thanks,
Santanu

Sample unit test code is shown below : 
```	
        private int CF = 500;
	private BufferedReader reader;
	private List<Double> samples = new ArrayList<Double>();
	

	private void readSamples() throws Exception {
		String line = reader.readLine();
		while (line != null) {
			double d = Double.parseDouble(line);
			samples.add(d);
			line = reader.readLine();
		}
	}
	
	private void run_test() {
		//create a TDigest
		MergingDigest m = returnNewDigest();
		for (int i = 0; i < samples.size() ; i++) {
			m.add(samples.get(i));
		}
		
		System.out.println("Median without split "+m.quantile(0.5));
	}
	

	private MergingDigest returnNewDigest() {
		return new MergingDigest(CF);
	}
	
	private void run_test_split() {
		int s1 = 15000;
		int s2 = 45000;
		int s3 = samples.size();
		
		
		MergingDigest m1 = returnNewDigest();
		
		for (int i=0 ; i < s1 ; i++) {
			m1.add(samples.get(i));
		}
		
		MergingDigest m2 = returnNewDigest();
		for (int i = s1 ; i < s2 ; i++) {
			m2.add(samples.get(i));
		}
		
		MergingDigest m3 = returnNewDigest();
		for (int i = s2 ; i < s3 ; i++) {
			m3.add(samples.get(i));
		}
		
		MergingDigest m4 = returnNewDigest();
		
		List<TDigest> l1 = new ArrayList<TDigest>();
		l1.add(m1);
		l1.add(m2);
		l1.add(m3);
		m4.add(l1);
		
		System.out.println("median with split (s1+s2+s3) "+m4.quantile(0.5));
		
		List<TDigest> l2 = new ArrayList<TDigest>();
		l2.add(m2);
		l2.add(m3);
		l2.add(m1);
		
		MergingDigest m5 = returnNewDigest();
		m5.add(l2);
		
		System.out.println("median with split (s2+s3+s1) "+m5.quantile(0.5));
	}
	
	@Test
	public void test() throws Exception {
		reader = new BufferedReader(new FileReader("src/test/resources/up.txt"));
		readSamples();
	    System.out.println("Number of samples "+samples.size());	
		run_test();
		run_test_split();
	}

```
The output of the test
```
Number of samples 60398
Median without split 30.101212824980962
median with split (s1+s2+s3) 30.585493893059724
median with split (s2+s3+s1) 30.232216458636376
```
If I select CF = 1500 , I get the following results : 
```
Number of samples 60398
Median without split 29.98999977111816
median with split (s1+s2+s3) 29.98999977111816
median with split (s2+s3+s1) 29.98999977111816
```

**Comment by tdunning** [comment]
It is impossible to precisely determine quantiles in a single pass through
the data, except in happy accidents.

As such, t-digest is an approximation algorithm and the errors are not
deterministic if you don't know the order of the data. As you increase the
compression factor, the errors should always decrease or at least not
increase.

The value you get will also vary somewhat if you rearrange how you add the
data via intermediate t-digests.

All of this is expected.
