### ISSUE TITLE
The "t" in "t-digest"

### ISSUE THREAD

**Issue by egnha** [tdunning/t-digest#95]
Not an issue, just a question about terminology:

As I understand it, a t-digest is a data structure motivated by that of a Q-digest, where the "Q" stands for "quantile." What does the "t" in "t-digest" stand for?

**Comment by tdunning** [comment]
Well I just wanted a letter of some kind. I couldn't use Q. And I'm a
complete egotist.

So I picked t. The initials TD seemed really good to me.

**Comment by egnha** [comment]
Ah, makes sense. ;-) Thanks.
