### ISSUE TITLE
Question about Welford's method

### ISSUE THREAD

**Issue by viniciusvdias** [tdunning/t-digest#98]
Hi, I was wondering if it makes sense to "remove" a sample from a t-digest.

Let me elaborate. My understanding is that, in t-digest, the centroid mean is calculated based on the Welford's method. So we get a new mean from a new point and the number of observations.

At first glance it looks like it is possible to isolate the previous mean from the recurrence relation and go back to a previous state by "removing" a sample.

However even if this is feasible, I am not sure how biased this would be, whether this would be stable or not. Does anyone have a comment about this?

Thank you,

**Comment by tdunning** [comment]
This is theoretically possible at the level of updating the centroid mean. But it will likely have disastrous effects on accuracy if you do it very much.

Typically there are two places where the desire to remove data comes up. The first is where you need to somehow restate some fraction of the past. The second is where you want to have rolling windows. The second case is much more common.

In both cases, I think that the best practice is never to try to remove individual samples from a t-digest, but rather to recompute from the bottom up. To make this reasonably fast, cache intermediate t-digests on relatively short time intervals and on interesting combinations of factors. This caching trick allows you to only do small amounts of recomputation when you remove data. For the rolling window case, you keep t-digests for short windows and you don't so much smoothly roll your window as you step the trailing edge forward in small discrete bumps. For instance, if you are looking at an hourly rolling window, you might have 5 minute bumps. For a monthly window, you might have daily bumps. Most of the time, you just add a new sample to the current small window and to the current rolling window. When it comes time to bump forward, you start a new t-digest for the new small window and recompute the t-digest for the rolling window by merging recent small window digests dropping out the oldest one from the previous computation. This has the effect of removing the oldest small window with well understood error processes. 

If you need to remove some old data, you simply have to recompute the affected small window digests and restart the rolling window if it was affected. 

This also allows you to compute a digest from any window in time.

Overall, I don't think that removal is worth the effort, but I am entirely willing to be over-ruled by evidence to the contrary.
